version: "3"
services:
  sillytavern-extras:
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    image: cohee1207/sillytavern-extras
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        REQUIREMENTS: requirements-complete.txt
        MODULES: caption,summarize,classify,sd,silero-tts,edge-tts,chromadb
    volumes:
      - "./cache:/root/.cache"
      - "/data/sili-extra/api_key.txt:/sillytavern-extras/api_key.txt:rw"
      #- "./chromadb:/chromadb"
    ports:
      - "5100:5100"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: python server.py --enable-modules=caption,summarize,classify,sd,silero-tts,edge-tts,chromadb
